version: '3.8'

services:
  # React Frontend
  frontend:
    build: ./frontend
    container_name: saggersrule-frontend
    ports:
      - "3000:3000"
    depends_on:
      - media-api
      - media-server
    networks:
      - saggersrule-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Node.js Media API
  media-api:
    build: ./media-api
    container_name: saggersrule-media-api
    ports:
      - "3200:3200"
    volumes:
      - ./media-storage:/app/media
      - ./processed-media:/app/processed
    environment:
      - NODE_ENV=production
      - PORT=3200
      - UPLOAD_PATH=/app/media
      - PROCESSED_PATH=/app/processed
      - REDIS_URL=redis://redis:6379
      - ALLOWED_EXTENSIONS=jpg,jpeg,png,gif,webp,mp4,mov,avi,mkv,flv,wmv,m4v
      - MAX_FILE_SIZE=104857600
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3036
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3200/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - redis
    networks:
      - saggersrule-network

  # Nginx Media Server
  media-server:
    image: nginx:alpine
    container_name: saggersrule-media-server
    ports:
      - "3036:3036"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./media-storage:/var/www/media
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3036/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      - media-api
    networks:
      - saggersrule-network

  # Redis Cache
  redis:
    image: redis:alpine
    container_name: saggersrule-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - saggersrule-network

networks:
  saggersrule-network:
    driver: bridge

volumes:
  media-storage:
  processed-media:
  redis-data: